#!/bin/sh

# https://github.com/gokcehan/lf/wiki/Previews

draw() {
  if [ "$TERM" == "xterm-kitty" ]; then
    kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
    exit 1
  fi

  chafa -f sixel -s "${w}x${h}" --animate off --polite on -t 1 --bg black "$1"
}

batorcat() {
  file="$1"
  shift
  if command -v bat > /dev/null 2>&1; then
    bat --color=always --pager=never "$file" "$@"
  else
    cat "$file"
  fi
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type "$file")" in
  image/*)
    draw "$file"
    ;;
  application/pdf)
    pdftotext "$1" -
    ;;
  *)
    batorcat "$1"
    ;;
esac

