#!/bin/sh

# https://github.com/gokcehan/lf/wiki/Previews
# https://github.com/xlucn/dotfiles/tree/master/lf

draw() {
  if [ "$TERM" == "xterm-kitty" ]; then
    kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
    exit 1
  fi

  chafa -f sixel -s "${w}x${h}" --animate off --polite on -t 1 --bg "#232831" "$1"
}

batorcat() {
  file="$1"
  shift
  if command -v bat > /dev/null 2>&1; then
    bat --color=always --pager=never "$file" "$@"
  else
    cat "$file"
  fi
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$file" in
  *.tar*)
    tar tf "$file"
    exit
    ;;
  *.zip)
    unzip -l "$file"
    exit
    ;;
  *.pdf)
    pdftotext "$file" -
    exit
    ;;
  *) ;;  # fallback to mime type
esac


case "$(file -Lb --mime-type "$file")" in
  image/*)
    draw "$file"
    exit
    ;;
  text/*)
    batorcat "$file"
    exit
    ;;
  *) ;;  # fallback to displaying mime type
esac

echo '----- File Type Classification -----'
file --dereference --brief -- "$file"
echo '------------------------------------'

