tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Powerful, lightweight programming language
brew "lua"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Platform built on V8 to build network applications
brew "node"
