#!/bin/zsh

# Updating dotfiles
function update_dotfiles() {
  cd ~/dotfiles/ && git pull && cd - &> /dev/null
}

# Add ssh shortcut
function add_ssh_shortcut() {
  mkdir -p ~/.ssh/
  [[ ! -e ~/.ssh/config ]] && touch ~/.ssh/config
  echo -n 'Nickname for the host: '
  read host_nickname
  echo -n 'Host URL: '
  read host_url
  echo -n 'Username for the server: '
  read -n username
  echo "Host $host_nickname
    Hostname $host_url
    User $username" >> ~/.ssh/config
  echo "${username}@${host_url} has been added to the SSH config! Try <ssh $host_nickname>."
}

# Custom trash function
function trash () {
  if [ ! -d "$HOME/trash_zsh/" ]
  then
    mkdir $HOME/trash_zsh/
  fi
  mv "$1" $HOME/trash_zsh/
  echo "$1" moved to trash!
}

function trash_empty() {
  if [ ! -d "$HOME/trash_zsh/" ]
  then
    echo 'Trash folder does not exist!'
  else
    rm -r $HOME/trash_zsh/
    mkdir $HOME/trash_zsh/
    echo 'Trash folder emptied!'
  fi
}

# Tar.gz
function tar_make() {
  tar -czvf "$1.tgz" "$1" # c for archive, z for gzip compression, -verbose, -f for output
}

function tar_unmake() {
  tar -xvf "$1"
}

function xrandr_external_on() {
  if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    echo -e "\033[0;31m[Fatal] You are on $OSTYPE\033[0m"
    return 1
  fi
  if [[ $# != 1 ]]; then
    echo -e "\033[0;32m[Usage] xrandr_external_on <output-name>\033[0m"
    echo -e "\033[0;32m\tRetreive the output name using xrandr command\033[0m"
  else
    xrandr --output $1 --auto --same-as eDP-1
  fi
}

function xrandr_external_off() {
  if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    echo -e "\033[0;31m[Fatal] You are on $OSTYPE\033[0m"
    return 1
  fi
  if [[ $# != 1 ]]; then
    echo -e "\033[0;32m[Usage] xrandr_external_off <output-name>\033[0m"
    echo -e "\033[0;32m\tRetreive the output name using xrandr command\033[0m"
  else
    xrandr --output $1 --off
  fi
}

######### Alias w hard-coded paths ##########
CACHE="~/Nextcloud/l1-cache/"
DAILY_WRITING_FOLDER="~/Nextcloud/dw-$(date +'%Y')/"
DOTFILES_FOLDER="~/dotfiles/"
QUICK_NOTES_PATH="$CACHE""quick-notes.md"
WIKI_PATH="~/Nextcloud/theo-vimwiki/"

alias l1="cd $CACHE"
alias dw="vim $DAILY_WRITING_FOLDER""index.md"
alias dot="cd $DOTFILES_FOLDER"
alias note="tmux display-popup -E -h 80% -w 80% 'nvim $QUICK_NOTES_PATH'"
alias note_no_tmux="nvim $QUICK_NOTES_PATH"
alias wiki="tmux display-popup -E -h 80% -w 80% 'vim $WIKI_PATH""index.md'"
alias wiki_no_tmux="vim $WIKI_PATH""index.md"

######### Alias ##########
alias cl="clear"
alias google="w3m google.com"
alias ls="ls -G"
alias l="ls -A -l -h" # All file except . and .., list view, display unit suffix for the size
alias nvi="nvim"
alias nvif="fd --type f --hidden --exclude .git | fzf-tmux --height 40% --reverse -p | xargs nvim"

