#!/bin/zsh

######### Alias ##########
alias cl="clear"
# Any $ commands in double quotes will be substituted in the startup and will be executed. So use single quotes
alias cdfzf='cd $(fzf --height 40% --reverse)'
alias google="w3m google.com"
alias ls="ls -G"
alias l="ls -l -a"
alias nvi="nvim"
alias nvif="fd --type f --hidden --exclude .git | fzf-tmux --height 40% --reverse -p | xargs nvim"

