#!/bin/zsh

# Custom trash function
trash () {
  if [ ! -d "$HOME/trash_zsh/" ]
  then
    mkdir $HOME/trash_zsh/
  fi
  mv "$1" $HOME/trash_zsh/
  echo "$1" moved to trash!
}

trash_empty() {
  if [ ! -d "$HOME/trash_zsh/" ]
  then
    echo "Trash folder does not exist!"
  else
    rm -r $HOME/trash_zsh/
    mkdir $HOME/trash_zsh/
    echo "Trash folder emptied!"
  fi
}

######### Alias ##########
alias cl="clear"
# Any $ commands in double quotes will be substituted in the startup and will be executed. So use single quotes
alias cdfzf='cd $(fzf --height 40% --reverse)'
alias google="w3m google.com"
alias ls="ls -G"
alias l="ls -l -a"
alias nvi="nvim"
alias nvif="fd --type f --hidden --exclude .git | fzf-tmux --height 40% --reverse -p | xargs nvim"

