#!/bin/zsh

export ZSH_PLUGIN_DIR=$HOME/.zsh_plugins

# Double check double check
function source_file() {
  [ -f "$1" ] && source "$1"
}

# Function to source or load a plugin
function theoshell_plug() {
  PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
  if [ -d "$ZSH_PLUGIN_DIR/$PLUGIN_NAME" ]; then
    source_file "$ZSH_PLUGIN_DIR/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
    source_file "$ZSH_PLUGIN_DIR/$PLUGIN_NAME/$PLUGIN_NAME.zsh"
  else
    git clone "https://github.com/$1.git" "$ZSH_PLUGIN_DIR/$PLUGIN_NAME"
  fi
}

