#!/bin/zsh

# Get more Oliver
function print_oliver() {
  olivers=(
    '
         \/   \/
         |\__/,|     _
       _.|o o  |_   ) )
      -(((---(((--------
    ' \
    # '
    #       \/ \/
    #       /\_/\ _______
    #      = o_o =  _ _  \     _
    #      (__^__)   __(  \.__) )
    #   (@)<_____>__(_____)____/
    #     ♡ ~~ ♡ OLIVER ♡ ~~ ♡
    # ' \
    '
         \/       \/
         /\_______/\
        /   o   o   \
       (  ==  ^  ==  )
        )           (
       (             )
       ( (  )   (  ) )
      (__(__)___(__)__)
    ' \
    # '
    #    \/   \/
    #    |\__/,|        _
    #    |_ _  |.-----.) )
    #    ( T   ))        )
    #   (((^_(((/___(((_/
    # ' \
    '
                             _
            |\      _-``---,) )
      ZZZzz /,`.-```    -.   /
           |,4-  ) )-,_. ,\ (
          `---``(_/--`  `-`\_)
    '
    )
    # 1. RANDOM is biased toward the lower index
    # 2. Array index in ZSH starts at 1
    oliver=${olivers[ $(( RANDOM % ${#olivers[@]} + 1 )) ]}
    echo -e "\033[0;31m${oliver}\033[0m"
}

# Inspired by https://github.com/G2-Games/welcome.sh/
function get_battery() {
  batlv=-1

  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    if [[ -a /sys/class/power_supply/BAT0/capacity ]]; then
      batlv=$(cat /sys/class/power_supply/BAT0/capacity)
    elif [[ -a /sys/class/power_supply/BAT1/capacity ]]; then
      batlv=$(cat /sys/class/power_supply/BAT1/capacity)
    fi
  elif command -v pmset &> /dev/null; then
    batlv=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)
  else
    batlv="No battery info"
    return
  fi

  if [[ $batlv -eq -1 ]]; then
    echo -e "\033[0;31mError, time to work on your dotfiles Theo\033[0m"
  elif [[ $batlv -ge 100 ]]; then
    echo -e "\033[0;33m${batlv}%\033[0m" # Yellow
  elif [[ $batlv -gt 40 ]]; then
    echo -e "\033[0;32m${batlv}%\033[0m" # Green
  else
    echo -e "\033[0;31m${batlv}%\033[0m" # Red
  fi
}

function greeting_msg() {
  print_oliver
  echo "
  \e[38;2;200;107;209mUser: $USER\e[0m
  \e[38;2;224;146;252;1mShell open: $(date -I) $(date +"%T")
  \e[38;2;159;121;147mBattery: $(get_battery)
  "
}

