#!/bin/zsh

autoload -Uz vcs_info

zstyle ':vcs_info:*' enable git
# Hook before every commands
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

zstyle ':vcs_info:*' check-for-changes true

zstyle ':vcs_info:*' unstagedstr ' *'
zstyle ':vcs_info:*' stagedstr ' +'
zstyle ':vcs_info:git:*' formats       '%b%u%c'
# Only displayed in Git action like rebase, merge, cherry-pick
zstyle ':vcs_info:git:*' actionformats '[%b | %a%u%c]'

########## Prompt Setting ##########
#000 #000000
#001 #800000
#002 #008000
#003 #808000
#004 #000080
#005 #800080
#006 #008080
#007 #c0c0c0
#008 #808080
#009 #ff0000
#010 #00ff00
#011 #ffff00
#012 #0000ff
#013 #ff00ff
#014 #00ffff
#015 #ffffff

#╭─ ⊄ theopn @ lightsaber hanging out in ~/dotfiles ⊅
#╰─ ⊄ (main *) HH:MM:SS ⊅ -> <command>
two_line_prompt="╭─ %F{008}⊊%f %F{214}%n%f %F{008}@%f %F{003}%m%f %F{008}ϵ%f %F{104}%~%f %F{008}⊋%f
╰─ %F{008}⊄%f %F{009}(\$vcs_info_msg_0_)%f %F{013}%*%f %F{008}⊅%f %F{008}<$%f "

PROMPT=$two_line_prompt

