##############################
#              __
#  ____  _____/ /_  __________
# /_  / / ___/ __ \/ ___/ ___/
#  / /_(__  ) / / / /  / /__
# /___/____/_/ /_/_/   \___/
##############################

echo "\e[036mWelcome\e[0m \e[32m$USER\e[0m!"

# Vim mode
bindkey -v

#source ~/dotfiles/zsh/functions-zsh

source ~/dotfiles/zsh/aliases-zsh
source ~/dotfiles/zsh/prompt-zsh

#add_plugin marlonrichert/zsh-autocomplete
source ~/.zsh_plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
